Logistic Regression
Data Dictionary
There are multiple variables in the dataset which can be cleanly divided in 3 categories:

Demographic information about customers
customer_id - Customer id

vintage - Vintage of the customer with the bank in number of days

age - Age of customer

gender - Gender of customer

dependents - Number of dependents

occupation - Occupation of the customer

city - City of customer (anonymised)

Customer Bank Relationship
customer_nw_category - Net worth of customer (3:Low 2:Medium 1:High)

branch_code - Branch Code for customer account

days_since_last_transaction - No of Days Since Last Credit in Last 1 year

Transactional Information
current_balance - Balance as of today

previous_month_end_balance - End of Month Balance of previous month

average_monthly_balance_prevQ - Average monthly balances (AMB) in Previous Quarter

average_monthly_balance_prevQ2 - Average monthly balances (AMB) in previous to previous quarter

current_month_credit - Total Credit Amount current month

previous_month_credit - Total Credit Amount previous month

current_month_debit - Total Debit Amount current month

previous_month_debit - Total Debit Amount previous month

current_month_balance - Average Balance of current month

previous_month_balance - Average Balance of previous month

churn - Average balance of customer falls below minimum balance in the next quarter (1/0)

In [17]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')
plt.style.use(['seaborn-bright','dark_background'])

In [18]:
data = pd.read_csv('churn_prediction_simple.csv')
data

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,days_since_last_transaction,...,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
0,1,3135,66,0,0.0,0,187.0,2,755,224.0,...,1458.71,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,0
1,6,2531,42,0,2.0,0,1494.0,3,388,58.0,...,1401.72,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,1
2,7,263,42,1,0.0,0,1096.0,2,1666,60.0,...,16059.34,15211.29,13798.82,0.36,0.36,857.50,286.07,15719.44,15349.75,0
3,8,5922,72,0,0.0,1,1020.0,1,1,98.0,...,7714.19,7859.74,11232.37,0.64,0.64,1299.64,439.26,7076.06,7755.98,0
4,9,1145,46,0,0.0,0,623.0,2,317,172.0,...,8519.53,6511.82,16314.17,0.27,0.27,443.13,5688.44,8563.84,5317.04,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22062,30295,2041,42,0,0.0,0,146.0,2,286,57.0,...,6777.41,8082.48,3515.03,0.51,90.10,1103.20,1183.04,7956.03,7431.36,0
22063,30297,1845,10,1,0.0,3,1020.0,2,1207,70.0,...,1076.43,2282.19,2787.70,0.30,0.30,0.30,0.30,1076.43,1076.43,0
22064,30298,4919,34,1,0.0,0,1046.0,2,223,14.0,...,4069.21,3668.83,3865.55,1.71,2.29,901.00,1014.07,3738.54,3690.32,0
22065,30299,297,47,0,0.0,2,1096.0,2,588,0.0,...,61017.55,53444.81,21925.81,4666.84,3883.06,168.23,71.80,61078.50,57564.24,1
22066,30301,2349,18,0,0.0,3,1232.0,2,474,59.0,...,2821.34,3213.44,4447.45,0.11,7.44,714.40,1094.09,2402.62,3260.58,1

In [19]:
data = data.dropna(how ='any')
data

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,days_since_last_transaction,...,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
0,1,3135,66,0,0.0,0,187.0,2,755,224.0,...,1458.71,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,0
1,6,2531,42,0,2.0,0,1494.0,3,388,58.0,...,1401.72,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,1
2,7,263,42,1,0.0,0,1096.0,2,1666,60.0,...,16059.34,15211.29,13798.82,0.36,0.36,857.50,286.07,15719.44,15349.75,0
3,8,5922,72,0,0.0,1,1020.0,1,1,98.0,...,7714.19,7859.74,11232.37,0.64,0.64,1299.64,439.26,7076.06,7755.98,0
4,9,1145,46,0,0.0,0,623.0,2,317,172.0,...,8519.53,6511.82,16314.17,0.27,0.27,443.13,5688.44,8563.84,5317.04,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22062,30295,2041,42,0,0.0,0,146.0,2,286,57.0,...,6777.41,8082.48,3515.03,0.51,90.10,1103.20,1183.04,7956.03,7431.36,0
22063,30297,1845,10,1,0.0,3,1020.0,2,1207,70.0,...,1076.43,2282.19,2787.70,0.30,0.30,0.30,0.30,1076.43,1076.43,0
22064,30298,4919,34,1,0.0,0,1046.0,2,223,14.0,...,4069.21,3668.83,3865.55,1.71,2.29,901.00,1014.07,3738.54,3690.32,0
22065,30299,297,47,0,0.0,2,1096.0,2,588,0.0,...,61017.55,53444.81,21925.81,4666.84,3883.06,168.23,71.80,61078.50,57564.24,1
22066,30301,2349,18,0,0.0,3,1232.0,2,474,59.0,...,2821.34,3213.44,4447.45,0.11,7.44,714.40,1094.09,2402.62,3260.58,1

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22067 entries, 0 to 22066
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     22067 non-null  int64
 1   vintage                         22067 non-null  int64
 2   age                             22067 non-null  int64
 3   gender                          22067 non-null  int64
 4   dependents                      22067 non-null  float64
 5   occupation                      22067 non-null  int64
 6   city                            22067 non-null  float64
 7   customer_nw_category            22067 non-null  int64
 8   branch_code                     22067 non-null  int64
 9   days_since_last_transaction     22067 non-null  float64
 10  current_balance                 22067 non-null  float64
 11  previous_month_end_balance      22067 non-null  float64
 12  average_monthly_balance_prevQ   22067 non-null  float64
 13  average_monthly_balance_prevQ2  22067 non-null  float64
 14  current_month_credit            22067 non-null  float64
 15  previous_month_credit           22067 non-null  float64
 16  current_month_debit             22067 non-null  float64
 17  previous_month_debit            22067 non-null  float64
 18  current_month_balance           22067 non-null  float64
 19  previous_month_balance          22067 non-null  float64
 20  churn                           22067 non-null  int64
dtypes: float64(13), int64(8)
memory usage: 3.5 MB

In [25]:
data['churn'].value_counts()/len(data)

churn
0    0.806317
1    0.193683
Name: count, dtype: float64

In [26]:
x = data.drop(columns = 'churn')
y = data['churn']

In [30]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
scaled_x = pd.DataFrame(scaler.fit_transform(x))

In [31]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(scaled_x,y,train_size = 0.8)
x_train

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
16398,0.843503,-0.135784,-0.727833,-0.802630,-0.361368,-0.747148,-0.086497,-0.316621,0.784716,-0.724280,0.258634,0.181576,0.201163,0.170188,-0.035793,-0.107423,-0.070836,-0.147213,0.226410,0.175527
7412,-0.571369,0.118808,0.797210,1.245905,-0.361368,-0.747148,0.685329,-0.316621,-0.963745,3.138719,-0.301520,-0.294564,-0.277110,-0.072973,-0.045521,-0.116196,-0.071081,-0.147771,-0.313637,-0.294038
12587,0.242050,-0.025690,-0.178817,1.245905,-0.361368,-0.747148,1.090943,-0.316621,-0.855364,-0.070542,-0.226063,-0.206302,-0.266289,-0.372929,-0.045522,-0.116198,-0.065344,-0.147774,-0.230940,-0.205128
13345,0.361654,-0.346588,-0.361822,1.245905,-0.361368,-0.747148,-0.480522,-0.316621,0.665277,0.072092,-0.298659,-0.291809,-0.294995,-0.304142,-0.045518,-0.116189,-0.071077,-0.133575,-0.310677,-0.279951
5480,-0.874099,-0.697512,-0.849836,1.245905,-0.361368,-0.747148,1.675027,1.176940,1.604203,-0.046770,-0.278949,-0.204967,-0.270822,-0.384648,-0.045517,-0.116187,-0.046128,-0.147759,-0.255080,-0.203856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,-1.550289,0.524778,0.370198,1.245905,-0.361368,-0.747148,1.090943,-0.316621,1.956992,3.198150,-0.205262,0.039283,-0.021874,0.046051,-0.045520,-0.116195,-0.033659,-0.147770,-0.140329,0.040355
11035,0.000783,-0.564899,0.736209,-0.802630,2.510529,-0.747148,0.685329,-0.316621,0.536990,-0.569760,0.495564,0.203791,0.313183,0.484899,0.038514,-0.112020,0.017486,-0.113716,0.361596,0.189190
21848,1.702246,0.437203,-0.788834,-0.802630,-0.361368,1.187415,0.312164,1.176940,-0.103338,-0.629191,-0.249985,-0.265408,-0.288730,-0.311616,-0.039745,0.386347,-0.069828,-0.140950,-0.272282,-0.254121
14881,0.603608,-0.141414,-0.361822,-0.802630,-0.361368,1.187415,0.509176,1.176940,0.779186,-0.795597,-0.275305,-0.337340,-0.242632,0.038458,-0.028814,-0.116197,-0.070782,-0.146884,-0.337441,-0.336448
2470,-1.343243,0.235157,-0.300821,-0.802630,1.553230,-0.747148,0.940286,-0.316621,-0.090067,-0.629191,-0.251783,-0.150555,-0.112041,-0.216247,-0.029083,-0.084555,-0.018100,-0.038429,-0.169841,-0.132519

In [33]:
from sklearn.linear_model import LogisticRegression as lr
classifier = lr(class_weight = 'balanced')

In [37]:
classifier.fit(x_train,y_train)
predicted_values = classifier.predict(x_test)
predicted_probabilities = classifier.predict_proba(x_test)

In [38]:
predicted_values

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [39]:
predicted_probabilities

array([[0.4471884 , 0.5528116 ],
       [0.63603482, 0.36396518],
       [0.59841322, 0.40158678],
       ...,
       [0.42440371, 0.57559629],
       [0.50470099, 0.49529901],
       [0.62135836, 0.37864164]])